### ISSUE TITLE
Error start script

### ISSUE THREAD

**Issue by WarL0ckNet** [LDarki/NodeJS-DuinoCoin-Miner#4]
```
/NodeJS-DuinoCoin-Miner/index.js:143
    let poolJson = json[];
                        ^

SyntaxError: Unexpected token ']'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

node --version
v14.18.2

npm --version
8.3.0

**Comment by LDarki** [comment]
Fixed, please check the last [commit](https://github.com/LDarki/NodeJS-DuinoCoin-Miner/commit/c0016545a0c4def7fb138aba4e9a2cdcb36d697e).

Ty.

**Comment by WarL0ckNet** [comment]
Thanks you
